In [ ]:
# https://stackoverflow.com/questions/43798377/one-hot-encode-categorical-variables-and-scale-continuous-ones-simultaneouely

In [3]:
import pandas as pd
import numpy as np

In [1]:
# Import libraries and download example data
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [4]:
dataset = pd.read_csv("https://stats.idre.ucla.edu/stat/data/binary.csv")
print(dataset.head(5))

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4


In [5]:
# Define which columns should be encoded vs scaled
columns_to_encode = ['rank']
columns_to_scale  = ['gre', 'gpa']

In [10]:
# Instantiate encoder/scaler
ohe    = OneHotEncoder(sparse=False)
scaler = StandardScaler()

In [11]:
# Scale and Encode Separate Columns
encoded_columns =    ohe.fit_transform(dataset[columns_to_encode])
scaled_columns  = scaler.fit_transform(dataset[columns_to_scale]) 

In [13]:
encoded_columns

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
scaled_columns

array([[-1.80026271e+00,  5.79072211e-01],
       [ 6.26668242e-01,  7.36929243e-01],
       [ 1.84013372e+00,  1.60514292e+00],
       [ 4.53316031e-01, -5.25927010e-01],
       [-5.86797234e-01, -1.20997415e+00],
       [ 1.49342930e+00, -1.02580761e+00],
       [-2.40092812e-01, -1.07842662e+00],
       [-1.62691050e+00, -8.15331569e-01],
       [-4.13445023e-01,  2.63095053e-04],
       [ 9.73372664e-01,  1.39466687e+00],
       [ 1.84013372e+00,  1.60514292e+00],
       [-1.28020608e+00, -4.46998495e-01],
       [ 1.49342930e+00,  1.60514292e+00],
       [ 9.73372664e-01, -8.15331569e-01],
       [ 9.73372664e-01,  1.60514292e+00],
       [-9.33501656e-01,  1.31810621e-01],
       [ 1.66678151e+00,  1.26311935e+00],
       [-1.97361492e+00, -2.18342584e+00],
       [ 1.84013372e+00,  9.47405285e-01],
       [-4.13445023e-01,  1.10526232e+00],
       [-7.60149445e-01, -5.78546021e-01],
       [ 6.26668242e-01,  6.31691222e-01],
       [ 1.06611610e-01, -1.49937871e+00],
       [ 8.

In [15]:
# Concatenate (Column-Bind) Processed Columns Back Together
processed_data = np.concatenate([scaled_columns, encoded_columns], axis=1)
processed_data

array([[-1.80026271,  0.57907221,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 0.62666824,  0.73692924,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 1.84013372,  1.60514292,  1.        ,  0.        ,  0.        ,
         0.        ],
       ...,
       [-1.10685387, -1.99925931,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.97337266,  0.68431023,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.10661161,  1.31573836,  0.        ,  0.        ,  1.        ,
         0.        ]])