<a href="https://colab.research.google.com/github/fernandovieira1/ML-e-DS-com-Python-de-A-a-Z/blob/master/Parte2_RL_simples_plano_saude.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install plotly --upgrade
# !pip install yellowbrick

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [3]:
base_plano_saude = pd.read_csv('/Users/fernandovieira/OneDrive/1. Educacao/INFO E ESTAT/IA Expert/ML-e-DS-com-Python-de-A-a-Z/Bases de dados/plano_saude2.csv')

In [4]:
base_plano_saude

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [5]:
x_plano_saude2 = base_plano_saude.iloc[:, 0].values

In [6]:
y_plano_saude2  = base_plano_saude.iloc[:, 1].values

In [7]:
np.corrcoef(x_plano_saude2, y_plano_saude2)

array([[1.       , 0.8199208],
       [0.8199208, 1.       ]])

In [8]:
x_plano_saude2.shape

(10,)

In [9]:
x_plano_saude2 = x_plano_saude2.reshape(-1, 1)

In [10]:
x_plano_saude2.shape

(10, 1)

In [11]:
x_plano_saude2 # idade

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [12]:
y_plano_saude2 # preco

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [13]:
from sklearn.svm import SVR

In [14]:
# Linear 
regressor_svr_saude_linear = SVR(kernel='linear')
regressor_svr_saude_linear.fit(x_plano_saude2, y_plano_saude2)

SVR(kernel='linear')

In [15]:
grafico = px.scatter(x=x_plano_saude2.ravel(), y=y_plano_saude2)
grafico.add_scatter(x=x_plano_saude2.ravel(), y=regressor_svr_saude_linear.predict(x_plano_saude2), name='Valor do plano de saúde de acordo com a idade')
grafico.show()

In [16]:
# Polinomial 
regressor_svr_saude_polinomial = SVR(kernel='poly', degree=4)
regressor_svr_saude_polinomial.fit(x_plano_saude2, y_plano_saude2)

SVR(degree=4, kernel='poly')

In [17]:
grafico = px.scatter(x=x_plano_saude2.ravel(), y=y_plano_saude2)
grafico.add_scatter(x=x_plano_saude2.ravel(), y=regressor_svr_saude_polinomial.predict(x_plano_saude2), name='Valor do plano de saúde de acordo com a idade')
grafico.show()

In [18]:
# Rbf 
regressor_svr_saude_rbf = SVR(kernel='rbf')
regressor_svr_saude_rbf.fit(x_plano_saude2, y_plano_saude2)

SVR()

In [19]:
grafico = px.scatter(x=x_plano_saude2.ravel(), y=y_plano_saude2)
grafico.add_scatter(x=x_plano_saude2.ravel(), y=regressor_svr_saude_rbf.predict(x_plano_saude2), name='Valor do plano de saúde de acordo com a idade')
grafico.show()

In [20]:
# Sigmoide 
regressor_svr_saude_sigmoide = SVR(kernel='sigmoid')
regressor_svr_saude_sigmoide.fit(x_plano_saude2, y_plano_saude2)

SVR(kernel='sigmoid')

In [21]:
grafico = px.scatter(x=x_plano_saude2.ravel(), y=y_plano_saude2)
grafico.add_scatter(x=x_plano_saude2.ravel(), y=regressor_svr_saude_sigmoide.predict(x_plano_saude2), name='Valor do plano de saúde de acordo com a idade')
grafico.show()

In [22]:
# Os algoritmos Regressão Linear, Decision Trees e Randon Forest são menos sensíveis à escala dos valores. No caso de SVM/SVR, faz-se necessário resolver isso.

In [29]:
from sklearn.preprocessing import StandardScaler

scaler_x = StandardScaler()
x_plano_saude2_scaled = scaler_x.fit_transform(x_plano_saude2)

scaler_y = StandardScaler()
y_plano_saude2_scaled = scaler_y.fit_transform(y_plano_saude2.reshape(-1,1))

In [30]:
x_plano_saude2_scaled

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [31]:
y_plano_saude2_scaled

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [32]:
# Rbf 
regressor_svr_saude_rbf = SVR(kernel='rbf')
regressor_svr_saude_rbf.fit(x_plano_saude2_scaled, y_plano_saude2_scaled.ravel())

SVR()

In [37]:
grafico = px.scatter(x=x_plano_saude2_scaled.ravel(), y=y_plano_saude2_scaled.ravel())
grafico.add_scatter(x=x_plano_saude2_scaled.ravel(), y=regressor_svr_saude_rbf.predict(y_plano_saude2_scaled), name='Valor do plano de saúde de acordo com a idade')
grafico.show()