In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
house_prices = pd.read_csv('/Users/fernandovieira/OneDrive/1. Educacao/INFO E ESTAT/IA Expert/ML-e-DS-com-Python-de-A-a-Z/Bases de dados/house_prices.csv')

In [ ]:
house_prices

In [ ]:
house_prices.columns

In [ ]:
# Vamos tentar prever por meio da metragem quadrada (sqft_living) da casa o preço dela (price)

In [ ]:
house_prices.describe()

In [ ]:
house_prices.isnull().sum()

In [ ]:
house_prices.isna().sum()

In [ ]:
house_prices.corr()

In [ ]:
figura = plt.figure(figsize=(25, 10))
sns.heatmap(house_prices.corr(), annot=True)

In [17]:
x_casas = house_prices.iloc[:, 3:19].values
x_casas.shape

(21613, 16)

In [16]:
y_casas = house_prices.iloc[:, 2].values
y_casas.shape

(21613,)

In [18]:
# Treinamento
from sklearn.model_selection import train_test_split

In [32]:
x_casas_treinamento, x_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(x_casas, y_casas, test_size=0.3, random_state=0)

In [33]:
x_casas_treinamento.shape, x_casas_teste.shape

((15129, 16), (6484, 16))

In [34]:
y_casas_treinamento.shape, y_casas_teste.shape

((15129,), (6484,))

In [31]:
from sklearn.linear_model import LinearRegression

In [35]:
# lm_s: regressão simples
# lm_m: regressão múltipla

lm_m = LinearRegression()
lm_m.fit(x_casas_treinamento, y_casas_treinamento)

LinearRegression()

In [36]:
# b0
lm_m.intercept_

5736222.703394298

In [37]:
# Coeficientes
lm_m.coef_

array([-3.08423090e+04,  3.66540816e+04,  1.12179159e+02,  8.00604120e-03,
        9.60355724e+03,  5.85441638e+05,  5.60621840e+04,  2.54795004e+04,
        1.01092121e+05,  6.96565321e+01,  4.25226266e+01, -2.60724691e+03,
        1.40070753e+01, -5.53557431e+02,  6.11778251e+05, -1.95564688e+05])

In [38]:
# R2 treinamento
lm_m.score(x_casas_treinamento, y_casas_treinamento)

0.7029888085955007

In [39]:
# R2 teste
lm_m.score(x_casas_teste, y_casas_teste)

0.6885414149062676

In [41]:
# PREVISOES
previsoes = lm_m.predict(x_casas_teste)
previsoes

array([ 383751.77768699, 1514216.17517446,  546921.96179113, ...,
        314968.57623303,  219405.55573556,  148128.83467043])

In [42]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [43]:
# MÉTRICAS
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [45]:
# MAE
mean_absolute_error(y_casas_teste, previsoes)

123888.4437748578

In [46]:
# MSE
mean_squared_error(y_casas_teste, previsoes)

42760757001.536095

In [47]:
# RMSE
np.sqrt(mean_squared_error(y_casas_teste, previsoes))

206786.74280895304