In [70]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [71]:
base_plano_saude2 = pd.read_csv('/Users/fernandovieira/OneDrive/1. Educacao/INFO E ESTAT/IA Expert/ML-e-DS-com-Python-de-A-a-Z/Bases de dados/plano_saude2.csv')

In [72]:
base_plano_saude2

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [73]:
x_plano_saude2 = base_plano_saude2.iloc[:, 0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:, 1].values

In [74]:
x_plano_saude2.shape, y_plano_saude2.shape

((10, 1), (10,))

In [75]:
from sklearn.preprocessing import PolynomialFeatures

In [76]:
poly = PolynomialFeatures(degree=4)

In [77]:
x_plano_saude2_poly = poly.fit_transform(x_plano_saude2)

In [78]:
x_plano_saude2_poly.shape

(10, 5)

In [57]:
# lm_s: regressão simples
# lm_m: regressão múltipla
# lm_p: regressão polinomial
from sklearn.linear_model import LinearRegression

In [81]:
lm_p = LinearRegression()
lm_p.fit(x_plano_saude2_poly, y_plano_saude2)

LinearRegression()

In [83]:
# bo
lm_p.intercept_

16561.97463791193

In [84]:
# coeficientes
lm_p.coef_

array([ 0.00000000e+00, -2.12242253e+03,  9.90404199e+01, -1.95058276e+00,
        1.40792541e-02])

In [85]:
# prevendo (pessoa 40 anos)
novo = [[40]]
novo = poly.transform(novo)
novo

array([[1.00e+00, 4.00e+01, 1.60e+03, 6.40e+04, 2.56e+06]])

In [86]:
lm_p.predict(novo)

array([1335.33958015])

In [88]:
# prevendo toda base de dados
previsoes = lm_p.predict(x_plano_saude2_poly)
previsoes

array([ 549.65035464,  345.85081575,  616.53845992,  975.8391595 ,
       1249.06759853, 1472.7272727 , 1894.51048941, 2973.2983677 ,
       5379.16083828, 9993.35664357])

In [89]:
grafico = px.scatter(x=x_plano_saude2[:, 0], y=y_plano_saude2)
grafico.add_scatter(x=x_plano_saude2[:, 0], y=previsoes, name='Regressão')
grafico.show()