In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import pickle

rede_neural = pickle.load(open('rede_neural_finalizado.sav', 'rb'))
arvore = pickle.load(open('arvore_finalizado.sav', 'rb'))
svm = pickle.load(open('svm_finalizado.sav', 'rb'))

In [3]:
with open('credit.pkl', 'rb') as f:
  x_credit_treinamento, y_credit_treinamento, x_credit_teste, y_credit_teste =pickle.load(f)

In [4]:
y_credit = np.concatenate([y_credit_treinamento, y_credit_teste], axis=0)
x_credit = np.concatenate([x_credit_treinamento, x_credit_teste], axis=0)

Simulando um novo registro e seus resultados

In [5]:
novo_registro = x_credit[0]
novo_registro

array([-1.3754462 ,  0.50630999,  0.10980934])

In [6]:
novo_registro = novo_registro.reshape(1, -1)

In [7]:
novo_registro.shape

(1, 3)

In [8]:
# 0: paga
# 1: não paga

In [9]:
resposta_rede_neural = rede_neural.predict(novo_registro)
resposta_rede_neural
# cliente com essas caracteristicas, vai pagar

array([0])

In [10]:
resposta_arvore = arvore.predict(novo_registro)
resposta_arvore
# cliente com essas caracteristicas, vai pagar

array([0])

In [20]:
resposta_svm = svm.predict(novo_registro)
resposta_svm
# cliente com essas caracteristicas, vai pagar

TypeError: predict() got an unexpected keyword argument 'probability'

Combinacao de classificadores

In [12]:
resposta_rede_neural[0], resposta_arvore[0], resposta_svm[0]

(0, 0, 0)

In [13]:
paga = 0
nao_paga = 0

# rede neural
if resposta_rede_neural[0] == 1:
    nao_paga += 1
else:
    paga += 1

# arvore
if resposta_arvore[0] == 1:
    nao_paga += 1
else:
    paga += 1


# svm
if resposta_svm[0] == 1:
    nao_paga += 1
else:
    paga += 1

# saídas
if paga > nao_paga:
    print('Cliente pagará o empréstimo')
elif paga == nao_paga:
    print('Empate')
else:
    print('Cliente não pagará o empréstimo')

Cliente pagará o empréstimo


Rejeição de classificadores

In [17]:
probabilidade_rede_neural = rede_neural.predict_log_proba(novo_registro)
probabilidade_rede_neural

confianca_rede_neural = probabilidade_rede_neural.max()
confianca_rede_neural

-5.551115123125785e-16

In [18]:
probabilidade_arvore = arvore.predict_log_proba(novo_registro)
probabilidade_arvore

confianca_arvore = probabilidade_arvore.max()
confianca_arvore

/Users/fernandovieira/Library/Python/3.8/lib/python/site-packages/sklearn/tree/_classes.py:1014: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)


0.0

In [19]:
probabilidade_svm = svm.predict_log_proba(novo_registro)
probabilidade_svm

confianca_svm = probabilidade_svm.max()
confianca_svm

# não entendi essa rejeição de classificadores

AttributeError: predict_proba is not available when  probability=False