In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
import pickle
with open('risco_credito.pkl', 'rb') as f:
    x_risco_credito, y_risco_credito = pickle.load(f)

In [3]:
x_risco_credito
# historia	divida	garantias	renda

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [4]:
y_risco_credito
# risco

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [5]:
# apagar os registros 'moderado' da variável y (registros linhas 2, 7, 11)
x_risco_credito = np.delete(x_risco_credito, [2, 7, 11], axis=0) # axis:0 (linha), 1 (coluna)
y_risco_credito = np.delete(y_risco_credito, [2, 7, 11], axis=0)

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
## Treinamento
logistic_risco_credito = LogisticRegression(random_state=1)
logistic_risco_credito.fit(x_risco_credito, y_risco_credito)

LogisticRegression(random_state=1)

In [8]:
logistic_risco_credito.intercept_

array([-0.80828993])

In [9]:
logistic_risco_credito.coef_
# historia	divida	garantias	renda

array([[-0.76704533,  0.23906678, -0.47976059,  1.12186218]])

In [10]:
## Previsoes
# historia boa, divida alta, garantias nenhuma, renda > 35
# historia ruim, divida alta, garantias adequada, renda < 15
previsoes1 = logistic_risco_credito.predict([[0, 0, 1, 2], [2,0, 0, 0]])
previsoes1


array(['baixo', 'alto'], dtype=object)