In [86]:
import os
import math

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [87]:
from sklearn.datasets import make_blobs

In [88]:
x_random, y_random = make_blobs(n_samples=200, centers=5, random_state=4)

In [89]:
x_random

array([[ 9.50048972e+00, -2.64303176e-01],
       [ 1.04083858e+01,  4.81956754e+00],
       [-5.27246366e+00, -2.01706265e-01],
       [-4.36574018e+00, -1.35715145e+00],
       [-5.25665254e+00, -3.59708240e+00],
       [ 1.08282804e+01,  3.84527696e+00],
       [-6.67057545e+00, -6.58753625e-01],
       [ 9.03763281e+00,  2.14664757e+00],
       [ 1.05327362e+01, -1.09583975e+01],
       [-3.92680269e+00, -8.44587573e-01],
       [ 2.96366327e+00, -3.76295852e+00],
       [ 1.08729182e+01, -8.47523410e+00],
       [ 9.31813516e+00, -8.76622032e+00],
       [-4.63975280e+00, -6.09076730e-01],
       [ 5.18378989e+00, -4.07833257e+00],
       [ 3.55418351e+00, -5.02889561e+00],
       [ 1.01719616e+01,  4.81287951e+00],
       [ 1.05820605e+01,  4.47715319e+00],
       [-4.48602989e+00, -1.71864312e+00],
       [ 3.55516222e+00, -7.14239365e+00],
       [ 3.69326445e+00, -4.80146761e+00],
       [-5.27978219e+00, -6.52043777e-01],
       [-5.03814228e+00, -2.98019370e-01],
       [ 8.

In [90]:
y_random

array([0, 1, 4, 4, 4, 1, 4, 0, 3, 4, 2, 3, 3, 4, 2, 2, 1, 1, 4, 2, 2, 4,
       4, 0, 0, 2, 2, 3, 0, 4, 0, 0, 1, 3, 2, 2, 4, 2, 1, 1, 1, 0, 2, 2,
       2, 3, 3, 1, 4, 1, 1, 2, 1, 0, 4, 1, 4, 0, 3, 0, 3, 4, 2, 1, 3, 4,
       0, 0, 4, 4, 1, 4, 1, 4, 1, 3, 2, 1, 4, 1, 2, 0, 4, 4, 0, 0, 2, 1,
       4, 1, 0, 2, 3, 1, 0, 3, 0, 3, 2, 0, 4, 1, 1, 3, 4, 2, 2, 4, 0, 4,
       1, 3, 4, 0, 1, 1, 0, 2, 2, 0, 2, 2, 3, 4, 2, 3, 1, 2, 3, 0, 0, 1,
       0, 3, 0, 3, 3, 4, 3, 1, 2, 1, 1, 4, 4, 3, 2, 1, 0, 4, 2, 0, 4, 4,
       3, 2, 3, 0, 3, 4, 1, 1, 0, 2, 4, 0, 1, 3, 2, 0, 2, 0, 1, 0, 4, 0,
       3, 0, 3, 1, 1, 3, 0, 4, 1, 2, 3, 2, 3, 3, 2, 2, 0, 3, 3, 3, 3, 3,
       3, 2])

In [91]:
len(x_random), len(y_random)

(200, 200)

In [92]:
type(x_random), type(y_random)

(numpy.ndarray, numpy.ndarray)

In [93]:
x_random.shape, y_random.shape

((200, 2), (200,))

In [94]:
grafico = px.scatter(x=x_random[:, 0], y=x_random[:, 1], width=1000, height=600)
grafico.show()

In [96]:
from sklearn.cluster import KMeans

In [101]:
scaler_blobs = StandardScaler()

In [102]:
kmeans_blobs = KMeans(n_clusters=4)
kmeans_blobs.fit(x_random)

KMeans(n_clusters=4)

In [103]:
centroides = kmeans_blobs.cluster_centers_
centroides

array([[ 9.94354117, -9.67105702],
       [ 9.5085904 ,  2.61221642],
       [-5.10744615, -1.23670878],
       [ 4.19521064, -5.71820513]])

In [105]:
rotulos = kmeans_blobs.labels_
rotulos

array([1, 1, 2, 2, 2, 1, 2, 1, 0, 2, 3, 0, 0, 2, 3, 3, 1, 1, 2, 3, 3, 2,
       2, 1, 1, 3, 3, 0, 1, 2, 1, 1, 1, 3, 3, 3, 2, 3, 1, 1, 1, 1, 3, 3,
       3, 0, 0, 1, 2, 1, 1, 3, 1, 1, 2, 1, 2, 1, 0, 1, 0, 2, 3, 1, 0, 2,
       1, 1, 2, 2, 1, 2, 1, 2, 1, 0, 3, 1, 2, 1, 3, 1, 2, 2, 1, 1, 3, 1,
       2, 1, 1, 3, 0, 1, 1, 0, 1, 0, 3, 1, 2, 1, 1, 0, 2, 3, 3, 2, 1, 2,
       1, 0, 2, 1, 1, 1, 1, 3, 3, 1, 3, 3, 0, 2, 3, 0, 1, 3, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 2, 0, 1, 3, 1, 1, 2, 2, 0, 3, 1, 1, 2, 3, 1, 2, 2,
       0, 3, 0, 1, 0, 2, 1, 1, 1, 3, 2, 1, 1, 0, 3, 1, 3, 1, 1, 1, 2, 1,
       0, 1, 0, 1, 1, 0, 1, 2, 1, 3, 0, 3, 0, 0, 3, 3, 1, 0, 0, 0, 0, 0,
       0, 3], dtype=int32)

In [121]:
grafico1 = px.scatter(x=x_random[:,0], y=x_random[:,1], color=rotulos)
grafico2 = px.scatter(x=centroides[:,0], y=centroides[:,1], size=[1, 1, 1, 1])
grafico3 = go.Figure(data=grafico1.data + grafico2.data)

grafico3.show()